### ISSUE TITLE
Cannot Connect to Default Configured HA Mosquitto

### ISSUE THREAD

**Issue by askpatrickw** [irimitenkan/picam2ctrl#4]
Two other people mentioned this on the Home Assistant Community.

The issue is someplace in this code. If I comment out these lines it runs for me. 

https://github.com/irimitenkan/picam2ctrl/blob/6c37a5268a3c769db729cfed3f52cedc51687b73/picamclient.py#L759-L766

I'm still looking at it, and will try to come back with a suggested fix.

**Comment by irimitenkan** [comment]
Thank you for helping. Since I'm not able to reproduce the connection issue, some questions:
- in your config username & pw is empty as well as mentioned by other users ?
- and if you comment lines 760-766 out it fixes the connection problem with empty user & pw ?

In your commit you removed the "insecure" setting in cfg file , but it is still  [referenced in line 767](https://github.com/irimitenkan/picam2ctrl/pull/5/commits/1634bb77cdad241c41166f10ffbe739b66cb438c#diff-f1e2d272e8901fb417efa5e1b17145ceb9cf674cba87eb286d1cb74f1321f9e2) ?

Hence other possible a solution might be to make lines with call of certfile stuff conditional only when username & pw is set  ?

**Comment by irimitenkan** [comment]
@askpatrickw 
In your [commit](https://github.com/irimitenkan/picam2ctrl/pull/5/commits/1634bb77cdad241c41166f10ffbe739b66cb438c#diff-f1e2d272e8901fb417efa5e1b17145ceb9cf674cba87eb286d1cb74f1321f9e2) call of 
`self.tls_set(cert_reqs=ssl.CERT_NONE)`
is removed but this is required in my environment even when username and password is not set.
But line

`self.tls_insecure_set(self.cfg.MQTTBroker.insecure)`

is not required for  both hence I disabled it. Please try if this fixes your problem,  available at next branch.

**Comment by askpatrickw** [comment]
I'm gong to go a different route...
